modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="vfa"
version="1.0.0"
displayName="Vergified Fabric API"
authors="Baran3575"
description='''A bridge allowing Fabric mods to run on NeoForge via VergConnector.'''

[[dependencies.vfa]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.vfa]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
